const Discord = require('discord.js')
const giphyRandom = require('giphy-random')

module.exports = {
    name: 'ping',
    description: "this is a ping command!",
    category: 'Fun',
    async execute(message, args, client, instance) {
        message.channel.send('pong!');
        JSON.stringify({
            created_at: 'Fri Feb 05 16:52:07 +0000 2021',
            id: 1357733755419431000,
            id_str: '1357733755419430914',
            text: 'WOOT #20?? LETS GOOOOOOOO 😆✨✨',
            source: '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
            truncated: false,
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: {
              id: 1103120130408673300,
              id_str: '1103120130408673280',
              name: 'its D A N S C ✨',
              screen_name: 'itsdansc',
              location: 'México',
              url: 'https://ko-fi.com/itsdansc',
              description: 'Artist/Student | 23 | 🇲🇽\n'   +
                'Comic, concept art, animation \n' +
                'Sonic, TMNT, Transformers 🤖🐢🦔💖\n' +
                '📧 hellodansc@gmail.com\n' +
                '\n' +
                'Ultra Magnus and Dinobot make me happy',
              translator_type: 'none',
              protected: false,
              verified: false,
              followers_count: 881,
              friends_count: 986,
              listed_count: 8,
              favourites_count: 4991,
              statuses_count: 2346,
              created_at: 'Wed Mar 06 02:28:28 +0000 2019',
              utc_offset: null,
              time_zone: null,
              geo_enabled: false,
              lang: null,
              contributors_enabled: false,
              is_translator: false,
              profile_background_color: '000000',
              profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
              profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
              profile_background_tile: false,
              profile_link_color: 'FAB81E',
              profile_sidebar_border_color: '000000',
              profile_sidebar_fill_color: '000000',
              profile_text_color: '000000',
              profile_use_background_image: false,
              profile_image_url: 'http://pbs.twimg.com/profile_images/1348737110912741377/MnHrAp9a_normal.jpg',
              profile_image_url_https: 'https://pbs.twimg.com/profile_images/1348737110912741377/MnHrAp9a_normal.jpg',
              profile_banner_url: 'https://pbs.twimg.com/profile_banners/1103120130408673280/1611782020',
              default_profile: false,
              default_profile_image: false,
              following: null,
              follow_request_sent: null,
              notifications: null
            },
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            quoted_status_id: 1357706860711850000,
            quoted_status_id_str: '1357706860711849985',
            quoted_status: {
              created_at: 'Fri Feb 05 15:05:15 +0000 2021',
              id: 1357706860711850000,
              id_str: '1357706860711849985',
              text: 'NEW SOURCE COUNTDOWN!\n' +
                "It's Friday, so it's a great time to round up the very best that TRANSFORMERS TWITTER had to… https://t.co/i2MtST5Gru",
              display_text_range: [ 0, 140 ],
              source: '<a href="https://www.hootsuite.com" rel="nofollow">Hootsuite Inc.</a>',
              truncated: true,
              in_reply_to_status_id: null,
              in_reply_to_status_id_str: null,
              in_reply_to_user_id: null,
              in_reply_to_user_id_str: null,
              in_reply_to_screen_name: null,
              user: {
                id: 4342242141,
                id_str: '4342242141',
                name: 'Sixo',
                screen_name: 'SixoTF',
                location: 'United Kingdom',
                url: 'https://linktr.ee/SixoTF',
                description: 'Transformers collector & photographer. Videos at https://t.co/0ojOWyBB1Y & articles at https://t.co/mjQ8Bz5q02 & https://t.co/GampN3oxBj. Collects vintage TF & modern MP/3P.',
                translator_type: 'none',
                protected: false,
                verified: false,
                followers_count: 8867,
                friends_count: 593,
                listed_count: 56,
                favourites_count: 87511,
                statuses_count: 42917,
                created_at: 'Tue Dec 01 18:12:29 +0000 2015',
                utc_offset: null,
                time_zone: null,
                geo_enabled: false,
                lang: null,
                contributors_enabled: false,
                is_translator: false,
                profile_background_color: '000000',
                profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
                profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
                profile_background_tile: false,
                profile_link_color: 'BC0909',
                profile_sidebar_border_color: '000000',
                profile_sidebar_fill_color: '000000',
                profile_text_color: '000000',
                profile_use_background_image: false,
                profile_image_url: 'http://pbs.twimg.com/profile_images/875467416091971589/oxElVPu6_normal.jpg',
                profile_image_url_https: 'https://pbs.twimg.com/profile_images/875467416091971589/oxElVPu6_normal.jpg',
                profile_banner_url: 'https://pbs.twimg.com/profile_banners/4342242141/1608028507',
                default_profile: false,
                default_profile_image: false,
                following: null,
                follow_request_sent: null,
                notifications: null
              },
              geo: null,
              coordinates: null,
              place: null,
              contributors: null,
              is_quote_status: false,
              extended_tweet: {
                full_text: 'NEW SOURCE COUNTDOWN!\n' +
                  "It's Friday, so it's a great time to round up the very best that TRANSFORMERS TWITTER had to offer in January. This month it's a bumper edition, with 75 tweets --&gt; https://t.co/7ke6Cy2XhZ https://t.co/Yjp2cEZjF1",
                display_text_range: [Array],
                entities: [Object],
                extended_entities: [Object]
              },
              quote_count: 4,
              reply_count: 2,
              retweet_count: 11,
              favorite_count: 44,
              entities: { hashtags: [], urls: [Array], user_mentions: [], symbols: [] },
              favorited: false,
              retweeted: false,
              possibly_sensitive: false,
              filter_level: 'low',
              lang: 'en'
            },
            quoted_status_permalink: {
              url: 'https://t.co/hX1MWCRfRB',
              expanded: 'https://twitter.com/SixoTF/status/1357706860711849985',
              display: 'twitter.com/SixoTF/status/…'
            },
            is_quote_status: true,
            quote_count: 0,
            reply_count: 0,
            retweet_count: 0,
            favorite_count: 0,
            entities: { hashtags: [], urls: [], user_mentions: [], symbols: [] },
            favorited: false,
            retweeted: false,
            filter_level: 'low',
            lang: 'en',
            timestamp_ms: '1612543927422'
          })
    }
}